/*
 * JS for startScreen generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '5f07be4b-1253-40a0-afc4-86e10de7eb68';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "startScreen",
    "location": "startScreen.html"
}];

function startScreen_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'number1': 'startScreen_number1',
        'number2': 'startScreen_number2',
        'addition_sign': 'startScreen_addition_sign',
        'subtraction_sign': 'startScreen_subtraction_sign',
        'multiplication_sign': 'startScreen_multiplication_sign',
        'Division_sign': 'startScreen_Division_sign',
        'mobilelabel_24': 'startScreen_mobilelabel_24',
        'mobileimage_25': 'startScreen_mobileimage_25',
        'mobilelabel_26': 'startScreen_mobilelabel_26'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.mappings["startScreen_addition_sign_onclick_mapping_3"] = {
        "homeScreen": "startScreen",
        "directions": [

        {
            "from_name": "Answer",
            "from_type": "SESSION_STORAGE",

            "to_name": "startScreen",
            "to_type": "UI",

            "mappings": [

            {

                "source": "$",
                "target": "$['mobilelabel_24:text']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["startScreen_subtraction_sign_onclick_mapping_3"] = {
        "homeScreen": "startScreen",
        "directions": [

        {
            "from_name": "Answer",
            "from_type": "SESSION_STORAGE",

            "to_name": "startScreen",
            "to_type": "UI",

            "mappings": [

            {

                "source": "$",
                "target": "$['mobilelabel_24:text']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["startScreen_multiplication_sign_onclick_mapping_3"] = {
        "homeScreen": "startScreen",
        "directions": [

        {
            "from_name": "Answer",
            "from_type": "SESSION_STORAGE",

            "to_name": "startScreen",
            "to_type": "UI",

            "mappings": [

            {

                "source": "$",
                "target": "$['mobilelabel_24:text']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["startScreen_Division_sign_onclick_mapping_3"] = {
        "homeScreen": "startScreen",
        "directions": [

        {
            "from_name": "Answer",
            "from_type": "SESSION_STORAGE",

            "to_name": "startScreen",
            "to_type": "UI",

            "mappings": [

            {

                "source": "$",
                "target": "$['mobilelabel_24:text']"

            }

            ]
        }

        ]
    };

    Apperyio.datasources = Apperyio.datasources || {};

    Apperyio.CurrentScreen = 'startScreen';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var startScreen_onLoad = function() {
            startScreen_elementsExtraJS();

            startScreen_deviceEvents();
            startScreen_windowEvents();
            startScreen_elementsEvents();
        };

    // screen window events


    function startScreen_windowEvents() {

        $('#startScreen').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function startScreen_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function startScreen_elementsExtraJS() {
        // screen (startScreen) extra code

    };

    // screen elements handler


    function startScreen_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#startScreen_number [name="addition_sign"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        $a.storage["input1"].update("$", $a.c15r($a.UIHandler.resolveGeneratedComponent('number1', this), 'get', 'text'))
                    } catch (e) {
                        console.error(e)
                    };
                    try {
                        $a.storage["input2"].update("$", $a.c15r($a.UIHandler.resolveGeneratedComponent('number2', this), 'get', 'text'))
                    } catch (e) {
                        console.error(e)
                    };

                    tempvar = Apperyio.storage.input1.get();
                    temp = Apperyio.storage.input2.get();
                    Apperyio.storage.Answer.set(parseInt(tempvar) + parseInt(temp));
                    Apperyio.processMappingAction(Apperyio.mappings["startScreen_addition_sign_onclick_mapping_3"]);

                }
            },
        }, '#startScreen_number [name="addition_sign"]');
        $(document).off("click", '#startScreen_number [name="subtraction_sign"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        $a.storage["input1"].update("$", $a.c15r($a.UIHandler.resolveGeneratedComponent('number1', this), 'get', 'text'))
                    } catch (e) {
                        console.error(e)
                    };
                    try {
                        $a.storage["input2"].update("$", $a.c15r($a.UIHandler.resolveGeneratedComponent('number2', this), 'get', 'text'))
                    } catch (e) {
                        console.error(e)
                    };

                    tempvar = Apperyio.storage.input1.get();
                    temp = Apperyio.storage.input2.get();
                    Apperyio.storage.Answer.set(parseInt(tempvar) - parseInt(temp));
                    Apperyio.processMappingAction(Apperyio.mappings["startScreen_subtraction_sign_onclick_mapping_3"]);

                }
            },
        }, '#startScreen_number [name="subtraction_sign"]');
        $(document).off("click", '#startScreen_number [name="multiplication_sign"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        $a.storage["input1"].update("$", $a.c15r($a.UIHandler.resolveGeneratedComponent('number1', this), 'get', 'text'))
                    } catch (e) {
                        console.error(e)
                    };
                    try {
                        $a.storage["input2"].update("$", $a.c15r($a.UIHandler.resolveGeneratedComponent('number2', this), 'get', 'text'))
                    } catch (e) {
                        console.error(e)
                    };

                    tempvar = Apperyio.storage.input1.get();
                    temp = Apperyio.storage.input2.get();
                    Apperyio.storage.Answer.set(parseInt(tempvar) * parseInt(temp));
                    Apperyio.processMappingAction(Apperyio.mappings["startScreen_multiplication_sign_onclick_mapping_3"]);

                }
            },
        }, '#startScreen_number [name="multiplication_sign"]');
        $(document).off("click", '#startScreen_number [name="Division_sign"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        $a.storage["input1"].update("$", $a.c15r($a.UIHandler.resolveGeneratedComponent('number1', this), 'get', 'text'))
                    } catch (e) {
                        console.error(e)
                    };
                    try {
                        $a.storage["input2"].update("$", $a.c15r($a.UIHandler.resolveGeneratedComponent('number2', this), 'get', 'text'))
                    } catch (e) {
                        console.error(e)
                    };

                    var tempVar = Apperyio.storage.input1.get();
                    var temp = Apperyio.storage.input2.get();
                    if (parseInt(temp) === 0) {
                        Apperyio.storage.Answer.set("you can't divide by 0,NOW IM FENA ROAST YO AHH");
                    } else {
                        Apperyio.storage.Answer.set(parseInt(tempVar) / parseInt(temp));
                    };
                    Apperyio.processMappingAction(Apperyio.mappings["startScreen_Division_sign_onclick_mapping_3"]);

                }
            },
        }, '#startScreen_number [name="Division_sign"]');

    };

    $(document).off("pagebeforeshow", "#startScreen").on("pagebeforeshow", "#startScreen", function(event, ui) {
        Apperyio.CurrentScreen = "startScreen";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    startScreen_onLoad();
};

$(document).off("pagecreate", "#startScreen").on("pagecreate", "#startScreen", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    startScreen_js();
});